# Generated by Django 3.1.4 on 2021-02-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bangalore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('bangalore_temperature', models.FloatField()),
                ('bangalore_wind_speed', models.FloatField()),
                ('bangalore_wind_direction', models.CharField(max_length=100)),
                ('bangalore_humidity', models.FloatField()),
                ('bangalore_dew_point', models.IntegerField()),
                ('bangalore_probablity_of_percipitation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chennai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('chennai_temperature', models.FloatField()),
                ('chennai_wind_speed', models.FloatField()),
                ('chennai_wind_direction', models.CharField(max_length=100)),
                ('chennai_humidity', models.FloatField()),
                ('chennai_dew_point', models.IntegerField()),
                ('chennai_probablity_of_percipitation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='delhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('delhi_temperature', models.FloatField()),
                ('delhi_wind_speed', models.FloatField()),
                ('delhi_wind_direction', models.CharField(max_length=100)),
                ('delhi_humidity', models.FloatField()),
                ('delhi_dew_point', models.IntegerField()),
                ('delhi_probablity_of_percipitation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kerala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('kerala_temperature', models.FloatField()),
                ('kerala_wind_speed', models.FloatField()),
                ('kerala_wind_direction', models.CharField(max_length=100)),
                ('kerala_humidity', models.FloatField()),
                ('kerala_dew_point', models.IntegerField()),
                ('kerala_probablity_of_percipitation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='madurai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('madurai_temperature', models.FloatField()),
                ('madurai_wind_speed', models.FloatField()),
                ('madurai_wind_direction', models.CharField(max_length=100)),
                ('madurai_humidity', models.FloatField()),
                ('madurai_dew_point', models.IntegerField()),
                ('madurai_probablity_of_percipitation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trichy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('trichy_temperature', models.FloatField()),
                ('trichy_wind_speed', models.FloatField()),
                ('trichy_wind_direction', models.CharField(max_length=100)),
                ('trichy_humidity', models.FloatField()),
                ('trichy_dew_point', models.IntegerField()),
                ('trichy_probablity_of_percipitation', models.IntegerField()),
            ],
        ),
    ]
